name: deploy blackfois app

on:
  push:
    branches:
      - master

jobs: 
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r . /var/www/html/
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 755 /var/www/html